#!/bin/bash

## Install ansible
python3 -m pip install --upgrade pip
python3 -m pip install ansible
ansible-galaxy collection install community.general
#/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# sudo ansible-pull -U https://github.com/adamWendell/ansible.git