#!/bin/bash

## Install ansible

xcode-select --install
curl -fsSL -o install.sh https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
brew install ansible

sudo rm -rf ~/.ansible/pull/ 2>/dev/null || true

ansible-pull -U https://github.com/adamWendell/ansible.git --vault-password-file .vault_pass

