- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:adamWendell/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
    
- name: Stowing 
  shell: bash ~/.dotfiles/mac
  tags:
    - install
    - dotfiles
